title: Readify
description: Mudahkan Membaca Buku
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Kelompok 3 Senproj
repo_url: "https://github.com/khalidrizki01/Readify"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
